#!/bin/sh

set -e

MAKE_JOBS="$1"
COMMIT="$2"
ARCH="$(uname -m)"

cd /deps && \
git clone https://github.com/zig-lang/zig && \
cd /deps/zig && \
git checkout "$COMMIT" && \
mkdir -p /deps/zig/build && \
cd /deps/zig/build && \
cmake .. \
    -DZIG_STATIC=on \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=/deps/local \
    -DCMAKE_INSTALL_PREFIX=/deps/install && \
make "$MAKE_JOBS" install && \
cd /deps/zig/build && \
./zig build docs && \
mkdir docs && \
./zig test ../lib/std/std.zig \
    -femit-docs=docs/std \
    -fno-emit-bin \
    --override-lib-dir ../lib && \
mv docs /deps/install/docs && \
mv ../zig-cache/langref.html /deps/install/docs/ && \
mv ../LICENSE /deps/install/ && \
cd /deps && \
chmod a+x install/bin/zig && \
VERSION="$(install/bin/zig version)" && \
DIRNAME="zig-linux-$ARCH-$VERSION" && \
mv install "$DIRNAME" && \
tar cvf "$DIRNAME.tar.xz" -I 'xz -0' "$DIRNAME" && \
chmod a+rw "$DIRNAME.tar.xz" && \
mv "$DIRNAME.tar.xz" /z/
